version: '2'
services:
  web:
    image: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
    - /data/mywork/nginx/html:/usr/share/nginx/html
    - /data/mywork/nginx/conf:/etc/nginx/conf.d
    - /data/mywork/nginx/logs:/var/log/nginx
    depends_on:
        - tomcat
    links:
        - tomcat
  tomcat:
    image: yancheng/jdk1.8-tomcat7:v1.0.0
    restart: always
    volumes:
     - /data/mywork/tomcat/webapp:/home/apache-tomcat-7.0.82/webapps
     - /data/mywork/tomcat/log:/home/apache-tomcat-7.0.82/logs
    depends_on:
      - mysql
    links:
    - mysql
  mysql:
    restart: always
    image: mysql
    ports:
     - "3306:3306"
    volumes:
       - /data/mywork/mysql/db:/var/lib/mysql
    environment:
        - MYSQL_ROOT_PASSWORD=5566
