version: '3'
services:
  ngnx-php:
    restart: always
    image: richarvey/nginx-php-fpm
    ports:
      - "80:80"
    depends_on:
    - mysql
    links:
    - mysql:mysql520
    volumes:
       - /data/mywork/html:/var/www/html      
  mysql:
    restart: always
    image: mysql:5.7
    ports: 
     - "3306:3306"
    environment:
        - MYSQL_ROOT_PASSWORD=520code.net  